baseURL = "https://kantnyr.cz/"
languageCode = "en-us"
title = "My Blog"
theme = "archie"
ignoreErrors = ['error-missing-instagram-accesstoken']
[params]
  mode = "light"  # nebo "dark"
  useCDN = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
